name: FullCircle Vision
favicon: null
layout_spectrum: 0.9822150748223066
typography_spectrum: 0.376746759749949
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25
  lightness: 0.49277321016415954
  saturation: 1
  rhythmicContrast: 0.6049215504899621
purpose: []
